sonar.projectKey=devops-formation-order
sonar.projectName=Order Service
sonar.sources=orders,config
sonar.tests=orders/tests
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage/unit/coverage.xml,coverage/integration/coverage.xml
sonar.coverage.exclusions=orders/tests/**,orders/migrations/**,config/settings/**,manage.py
