replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

configmap:
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "pgcat.dev.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "order"
  POSTGRES_SSLMODE: "disable"
  CORS_ALLOW_ALL_ORIGINS: "TRUE"
  LOG_LEVEL: "DEBUG"
  ENV_NAME: "dev"

hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60
